### ISSUE TITLE
site importer ignores scores from oct 16th

### ISSUE THREAD

**Issue by whiteou7** [beer-psi/kt-chunithm-site-importer#1]
Title. 

Clicking on import all pbs or import recent scores simply shows "nothing to import". Scores from oct 17th got imported without any issues. So far I've tried reinstalling the script, tampermonkey, reconfiguring api key and changing browser.

**Comment by beer-psi** [comment]
All scores in the recent tab was wiped on 17/10, when upgrading to LUMINOUS PLUS. If you didn't import your scores before then, they are lost for good. Do a PB import.
